export enum CardSteps {
  DEFAULT,
  SELECT_CARD_LIST,
  SELECT_CARD_FORM,
  SELECT_CARD_INFO,
  ADD_CARD_FORM,
  SELECT_CARD_VOUCHER,
  ADD_CARD_LIST,
}

export enum ActivityPaymentSteps {
  DEFAULT,
  ACTIVITY_PAYMENT_FORM,
  ACTIVITY_PAYMENT_SELECT_CARD_LIST,
  ACTIVITY_PAYMENT_VOUCHER,
  ACTIVITY_PAYMENT_FAIL,
}
